version: "3.8"

services:
  php:
    image: php:fpm-alpine
    container_name: php
    volumes:
      - ./nyoba/:/var/www/html/
    networks:
      - app

  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nyoba/:/var/www/html/
    networks:
      - app
    ports:
      - "80:80"

networks:
  app:
    name: app-net
